src/spectrum.rs

Allows creating `Spectrum`s from measured data without resorting to interpolation or going via the fallible `TryFrom<&[f64]>`. 
Solves part of the problem in #1

Add `Spectrum::new` and implement `From<[f64; 401]>` on `Spectrum` for simpler creation

---

src/rgb.rs

I found it rather hard to extract the actual RGB values from the `RGB` type. The only options I could find was to get the very complex `Vector3` type from `nalgebra`, or to get the lossy `u8` version with gamma applied. Is there any method I missed? Is there maybe some good reason why a user should not use those values directly? I need them to render the colors in OpenGL. So floats are what I'm after.
Here I add a very straight forward getter for accessing the raw color channel values at their full resolution and with a standard type format.
I also added tests to prevent regressions. For the `[u8; 3]` case I did not verify if the resulting values (with gamma applied) made sense. I just used what it returns right now and assume the implementation is currently correct.

Add a way to extract the raw float values from the RGB type

---

Cargo.toml
README.md
src/cct.rs
src/cri.rs
src/xyz.rs

Running `cargo test` produced a bunch of compilation errors. Some tests and examples assumed certain features were enabled, while they might not be. This PR fixes that by applying the conditional compilation guards needed.

Fix tests broken due to inactive features/conditional compilation

---

.github/workflows/build-and-test.yml
Cargo.toml
src/cct.rs

Because of things such as #5, I figured it would be very helpful to have a CI in place, to catch issues before they are merged. For obvious reasons, this PR will fail until #5 is merged and this PR is rebased on top of it. I submit it as different PRs, since fixing existing issues is one thing, and discussing a CI setup is another.
Sadly, this also fails very often due to #6. We can discuss those separately. This CI job won't do much good until both #5 and #6 are fixed, that's why I mark it as a draft PR for now.
This Github Actions workflow is more or less a copy-paste of what I usually use. Something I have refined over the years and that I find provides a good baseline for validating if PRs towards Rust crates break something.
Here is a link to one of my crates, showing how I usually …

Add CI job to catch build, test and documentation issues in PRs

---

.github/workflows/build-and-test.yml
Cargo.lock
Cargo.toml
src/cct.rs

Follow up to #6.
Commit 317bd34 stopped testing the mired/d search space randomly and instead probed 100 fixed points generated by a PRNG with a fixed seed. This makes it hard to see what points are probed, and why these specific points were chosen. It's always the same 100 values, but the values are not obvious in the code. Not to mention that it costs having `rand` as a `dev-dependency` even though no real randomness was needed.
This PR takes a stab at trying to simplify this test. It essentially does two things:
1. Empirically find roughly where in the search space the error is the highest. Create one dedicated test for this point, to make sure it stays within the error margin.
2. Replace the test for 100 "random" probe points with going over the entire search space, in discrete steps, …

Exhaustively try CCT space with an even spaced step instead of random samples

---

src/cri.rs
src/rgbspace.rs
src/xyz.rs

I found a few places in the code that followed the pattern: array with size known at compile time -> iterate over (loses known length) -> allocate result to heap -> try to convert back to array with the same size. Since the size is known at compile time, it can quite often be processed in place while keeping the known length.
The benefits this PR brings includes reducing heap allocation. There are no benchmarks, but I suspect this is noticeably faster. It also removes a panicking code path. I have not checked if the compiler can optimize the possible panic or not from the previous version of the code though. I also think this code is simpler (subjective), and shorter.
Most of the trick here is `array::as_ref` which allows us to `map` over an array without being able to own the array.
I …

Reduce allocation by working directly on arrays instead of `collect()`ing

---

src/cam.rs
src/xyz.rs

Previously if a slice of len < 3 was passed in, the constructor would panic. If a slice of len > 3 was passed in, all elements after the third would just be silently ignored. This seems lossy and error prone.
If requirements can be encoded in the type system (without introducing a lot of unergonomic APIs), then they should IMO. This allows the compiler to catch more problems with the code, and just the function signatures themselves tell the reader a lot more about what is expected from the API.
`XYZ::new` is now truly infallible and it will use all the passed in data.
If construction from slices are needed to make the API more ergonomic, it can be added! But I did not know of any use case where this would be really helpful, so I did not add one for now. If one is added I think it should …

Make `XYZ::new` take arrays instead of slices

---

src/illuminant.rs
src/observer.rs
src/rgb.rs
src/spectrum.rs
src/stimulus.rs
src/xyz.rs

PR tightly related to #13. Just another batch of Clippy warnings fixed. Again, the lint name that is being addressed can be found in each commit message, and the documentation for that lint can be found at https://rust-lang.github.io/rust-clippy/master/index.html
The last commit is unrelated to Clippy. I found some helpful comments that would be great to see in the docs, so I made them doc comments (`//` -> `///`)

Fix more clippy warnings

---

examples/cri.rs
src/cam.rs
src/cct.rs
src/colorant.rs
src/gamma.rs
src/geometry.rs
src/illuminant.rs
src/lab.rs
src/lib.rs
src/observer.rs
src/rgbspace.rs
src/spectrum.rs
src/std_illuminants.rs
src/viewconditions.rs

Clippy is a great Rust linter. It's part of the standard distribution of Rust. It can really help find bugs, code smells and unidiomatic code. I ran it against this library and fixed some of the things it picked up on. I did not fix all of its warnings in order to keep the PR size down a bit at least, and because I don't have more time right now :)
I hope we can fix all clippy warnings, and then add a CI check to enforce no lint warnings in the code :sparkles: 
This PR is probably easiest reviewed per commit. Since each commit deal with one clippy warning, and they are not related to each other. Too read more about all lint rules and why they are the way they are, you can check them out here: https://rust-lang.github.io/rust-clippy/master/index.html

Fix some clippy warnings

---

src/colorant.rs
src/rgb.rs
src/spectrum.rs

The Clippy linter pointed out that the direct `Spectrum::mul` method could be confusing for users, as it can be confused for the very common `Mul::mul` method. And `Spectrum` implements `Mul` also, and they did the same thing. So I removed both `mul` and `mul_f64` from `Spectrum` directly, recommending users to use the methods on the corresponding `Mul` implementations.
The above removal caused some errors. Previously if you had a `Colorant` value, and you called `mul` on it, it could via the `Deref<Target=Spectrum>` implementation figure out that it should defer the `Colorant` to a `Spectrum` and then call the explicit `mul` method. But it can't do this inference when the method on `Spectrum` comes from a trait. I then started looking into these `Deref` implementations and seeing if they …

Clearer colorant to spectrum conversion

---

src/colorant.rs
src/illuminant.rs
src/spectrum.rs

Both `Illuminant` and `Colorant` are just wrappers around a `Spectrum`, with some special meaning (and sometimes constraints on the spectral values). However, there was no simple way to create these types from spectrums. Both types had `TryFrom<&[f64]>`, but this has a number of problems IMHO:
1. It's hard to find the `From`/`TryFrom` implementations in the documentation as they are mixed up with loads of trait implementations.
2. It performs conversions in multiple steps at once: `slice of unknown length` -> `array of known length` -> `Spectrum` -> `Illuminant/Colorant`. This makes it impossible to go directly from a `Spectrum` to an `Illuminant/Colorant`. This is both a problem in terms of paying for data validation when you might already know you have the correct data, and it's harder …

Add helpful constructors to `Illuminant` and `Colorant`

---

CHANGELOG.md

It would be great to cut a new release rather soon. A ton of improvements have happened since `0.0.3` was released! But the more releases there are, and the more the API changes, the more important it becomes to have a changelog. This helps library users a lot when upgrading their dependencies.
I copied the format I usually use for Rust crates. keepachangelog.com is an established standard, so it's nice to stick to something someone else thought through IMHO.
I listed the dates for all the previous releases. But I did not make the effort to list all their changes. That can be added later if someone feel it's important. For me it's more important to document changes from now and going forward :)

Adding a changelog

---

CHANGELOG.md
src/xyz.rs

I'm not sure if this change is sound. So maybe regard this as question primarily, and a change suggestion secondarily :)
The following code shows the problem:
```rust
use colorimetry::prelude::*;
fn main() {
let observer = Observer::Std1931;
let nm_min = observer.data().spectral_locus_nm_min();
let nm_max = observer.data().spectral_locus_nm_max();
for nm in nm_min..=nm_max {
let xyz_in = observer.data().spectral_locus_by_nm(nm).unwrap();
let [x, y] = xyz_in.chromaticity();
let xyz_out = XYZ::try_from_chromaticity(x, y, None, Some(observer)).expect("Oh no!");
}
}
```
This code panics with:
```
thread 'main' panicked at examples/spectral_locus.rs:11:78:
Oh no!: InvalidChromaticityValues
```
For some XYZ values along the spectral locus, the sum of the chromaticity coordinates is exactly 1.0. …

Relax chromaticity value verification in `try_from_chromaticity`

---

CHANGELOG.md
src/error.rs

I found that a decent amount of the large collection of error cases sits unused. I'm guessing that these are historical remains from previous iterations of the code, but I did not look too much in the git history :)
I figured we better clean these up. If they are needed for some yet-to-be-written functionality, they can be added back once that functionality is in place IMHO.

Remove the `CmtError` variants that are never used

---

src/cct.rs
src/observer.rs

Clippy was giving off a bunch of these warnings:
```
warning: a `const` item should not be interior mutable
--> src/cct.rs:265:5
|
265 |     const UVM_EMPTY: OnceLock<[f64; 3]> = OnceLock::new();
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: consider making this a static item
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#declare_interior_mutable_const
= note: `#[warn(clippy::declare_interior_mutable_const)]` on by default
```
See the [link in the warning](https://rust-lang.github.io/rust-clippy/master/index.html#declare_interior_mutable_const) on why it's dangerous to put types providing interior mutability in `const`s. These could not be made `static`, since they do need to *copied* to every element in their …

Simplify internal `OnceLock` caching and fix a clippy warning

---

CHANGELOG.md
examples/primaries.rs
src/observer.rs
src/rgb.rs
src/rgbspace.rs
src/stimulus.rs

Clippy warned that `LazyLock<HashMap<&str, ([[f64; 2]; 3], StdIlluminant)>>` was a very complex type and should be considered for refactoring or being made into a type alias. So I looked closer at the `XY_PRIMARIES` code. I came to the conclusion that these values are probably better exposed as dedicated methods on the existing `RgbSpace` type. This allows us to get rid of both the lock and the heap allocated map.
Where one would previously write `XY_PRIMARIES.keys()` one can now instead use `RgbSpace::iter()` along with the new methods `name`, `primaries_chromaticity` and `white` to obtain the same information. This ties the data closer to the `RgbSpace` type, instead of being a standalone static.
Having dedicated methods for each type of data, instead of returning tuples, allows writing …

Replace public static `XY_PRIMARIES` with methods on space enum

---

.github/workflows/linting.yml
src/cri.rs
src/illuminant.rs
src/munsell_matt.rs
src/rgb.rs
src/spectrum.rs

This PR fixes all remaining warnings that clippy emit with its default config. But this PR also depends on #26 and #25, since they also fix clippy warnings. So this CI will fail until those other two are merged and this is rebased on top latest `main` again.
Since all clippy will be fixed if all these three PRs are merged, I went ahead and added clippy to the CI. This allows catching code smells and other problems before they are merged.

Fix remaining clippy warnings and add clippy to CI

---

src/rgbspace.rs

The single static `OnceLock` was shared between all instances of RgbSpaceData. As a result, every invocation of primaries_as_colorants always returned the same value (the colorants of the first call to this method). The closure passed to `PRIMARY_FILTERS.get_or_init(|| ...)` is only called the first time `primaries_as_colorants` is called, and then the same value is returned on subsequent calls.
Consider this example code:
```rust
use colorimetry::prelude::RgbSpaceData;
fn main() {
let srgb_primaries = RgbSpaceData::srgb().primaries_as_colorants();
let adobe_primaries = RgbSpaceData::adobe_rgb().primaries_as_colorants();
dbg!(srgb_primaries);
assert_eq!(srgb_primaries, adobe_primaries);
}
```
You can run this and the `assert_eq` will pass. You can also observe that if you change the order …

Fix bug in `RgbSpaceData::primaries_as_colorants` by removing caching

---

CHANGELOG.md
src/observer.rs
src/rgb.rs
src/stimulus.rs

The caching made the computed matrixes only valid for the first observer they were called on. This is the exact same problem as in #35 and #31. Statics can't be used to store values that depend on data in `self` when `self` can change between multiple calls to the same code.

Remove caching from `xyz2rgb` and `rgb2xyz` to fix bug

---

CHANGELOG.md
examples/spectral_locus.rs
src/observer.rs
src/xyz.rs

This PR is very similar to #31. Caching computed results in a static attached to a type that have multiple variants cause the caching to store the value for the first variant it's called on, and then return that value for all subsequent method calls, even if it's called on a different observer. Again, correctness must be more important than performance.
I added `EnumIter` implementation for `Observer` to easily iterate over all observers. Other similar enums implement this, so I figured this one could as well. Makes the example easier to implement.
This PR also tries to fix #34.

Fix multiple bugs around `spectral_locus_index_min` and `spectral_locus_index_max`

---

CHANGELOG.md
README.md
src/rgb.rs
src/spectrum.rs
src/xyz.rs

I find myself quite often writing code like:
```rust
let xyz = compute_tristimulus_values(...);
let [x, y, z] = xyz.values();
// Do something with the values
```
And the equivalent for RGB. Needing a completely separate statement and three extra variables just to get access to the raw values is proving a bit inconvenient for me. So I wanted to suggest the addition of these very simple getters.
I found it surprising that `XYZ::values()` does not just return the raw values untouched, but rather normalize them. That does not seem optimal for a simple getter. If a user fetch the values with `values()` and check something on them, and then use the `XYZ` instance for something else, they might not be aware that the values they are using are not the same ones they inspected earlier. I think not …

Add ergonomic value getters to `XYZ` and `RGB`

---

CHANGELOG.md
README.md
src/error.rs
src/lib.rs
src/observer.rs
src/prelude.rs
src/rgb.rs
src/spectrum.rs
src/stimulus.rs
src/widergb.rs
src/xyz.rs

Remove  (old) `RGB::from_xyz` method, which required XYZ values to be in the range from 0.0 to 1.0.
Use `XYZ::rgb` instead, which uses the reference illuminance for scaling.
Improved documentation.

Remove `RGB::from_xyz` method, add WideRgb for uncontrained rgb values

---

src/observer.rs

This test fails, due to #36. I still don't know what's wrong but I figured I'll submit a PR with the test shat shows the issue as a start. We **can't merge this just yet**, since that would break the CI. We need to figure out why the XYZ->RGB conversion fails and fix it ifrst.

Extend test_spectral_locus_to_rgb test to test for all observers

---

CHANGELOG.md
examples/spectral_locus.rs
src/data/observers.rs
src/error.rs
src/observer.rs
src/xyz.rs

My main aim with this change was to add back correct and fast caching of the computation of the lower and upper wavelength limits of the spectral locus. However, there were a few other things about the API of the `ObserverData` regarding the access of spectral locus values as well that has been an itch for me when learning and using this library. So I checked if I could improve on it in ways that I would find easy to understand and ergonomical to use. I hope you'll like it and that we can find some nice improved API that we both like :blush: 
Sadly it all went into one pretty big commit. It was really hard to make one change without making the others. But I'll explain each change here:
* Make `spectral_locus_index_min`, `spectral_locus_index_max` and `spectral_locus_by_index` private. Was …

Add caching of spectral locus min/max and improve API of access to spectral locus and CMFs

---

CHANGELOG.md
src/widergb.rs

Similar to #42 but for the new `WideRgb` type.

Add r(), g() and b() helper methods to WideRgb, along with tests

---

CHANGELOG.md
src/cri.rs
src/observer.rs
src/widergb.rs
src/xyz.rs

When I in some previous PRs and issues argued for splitting some types up into multiple types, and enforcing constraints on their values harder, it was to have the compiler help the user catch issues. And for the code to spell out what happens better when using the library. This includes not automagically converting between types where the user probably want to make a choice about how the conversion happens, and not automagically converting multiple steps in one go etc.
Instead I think that providing good documentation about what the user needs to do to convert between types to achieve their desired behavior, and providing logical, well named, one-step-at-a-time conversion methods, helps the user much more. We mostly have these well documented steps available! And that's awesome …

Remove `impl From<WideRgb> for [u8; 3]` in favor of being more explicit

---

src/colorant.rs
src/cri.rs
src/illuminant.rs
src/munsell_matt.rs
src/physics.rs
src/spectrum.rs

This PR replaces many hardcoded integer literals with the values `380` or `780` with the corresponding `SPECTRUM_WAVELENGTH_RANGE.start()` and `SPECTRUM_WAVELENGTH_RANGE.end()`. This makes the code a bit longer in some places for sure. But repeating hard coded literals is often a code smell. This way the intent might become clearer. This also allows changing what wavelength range the library supports easier (hypothetical change by us or someone forking the library).

Use existing `SPECTRUM_WAVELENGTH_RANGE` instead of repeating the `380`/`780` integer literals

---

CHANGELOG.md
src/spectrum.rs

I don't know how you use `colorimetry` exactly. So maybe the existing behavior is really desirable for you. But I find the way that the indexing into a `Spectrum` currently works to be uncommon, and can easier lead to harder-to-debug bugs when using the library.
I most of the time prefer failing loudly rather than failing silently. Failing silently here meaning that when the user does something wrong, you try to smooth it over and do some "best effort guess" instead of throwing an error. This might lead a user who has some indexing bug to scratch their head for hours about why the data they get out looks so strange. If we instead throw an error they will directly see that something is wrong with their code computing the wavelength they index by.
Is there any real use case where a user …

Make indexing into a Spectrum with invalid indices panic

---

CHANGELOG.md
src/widergb.rs

I found a bug in the new `WideRgb::compress` method. Previously `WideRgb` instances with only positive channel values would have its lowest channel value invalidly scaled down to 0.0. And instances with only values below 1.0 would have its highest channel value invalidly scaled up to 1.0.
I confirmed this by adding quite a lot of tests. The amount of tests are actually justified in my opinion. Because I added them one at a time when trying to fix the bug, but there was always some more edge case that my fix failed to correct for. So I tried to be as exhaustive as possible.
I then applied the simplest fix I could find that made all tests pass. However, I thought the resulting code was very complex compared to the naive implementation I described in …

Fix `WideRgb::compress` bug

---

Cargo.lock
Cargo.toml
benches/widergb.rs

`criterion` just released version `0.6.0` with a fix for the `minimal-versions` issue! So now it should be possible to add benchmarks with it, and keep our CI intact.
If you believe a benchmarking suite is worth having. Currently in this state alone, it does not provide very much value. The `compress` method is already benchmarked, and as far as we can tell correct. So it won't likely see much churn going forward. But it might be interesting to add benchmarks for some other computations this library has, and be able to catch performance regressions or better evaluate improvements.
If there is something in particular you feel like it would be interested in knowing the performance of. Just tell me, and I can try to add a benchmark for it in this PR as well.

Add benchmarks for `WideRgb::compress`

---

src/xyz.rs

Back in #42 I added `XYZ::y` along with getters for the other two values. I had completely missed there was a specific `XYZ::luminous_value` method that returns the exact same thing. I don't think there should be two methods returning the very same thing. The API surface grows without providing anything useful.
In this PR I opted for removing the older of the methods, since the `y` method is consistent in naming with the `x` and `z` methods.

Remove `XYZ::luminous_value`, since it was identical to `XYZ::y`

---

src/xyz.rs

The docs were outdated, since we removed the normalization from `XYZ::values`.

Fix documentation on `From<XYZ> for [f64; 3]`

---

CHANGELOG.md
src/cam.rs
src/colorant.rs
src/colorant/munsell_matt.rs
src/error.rs
src/geometry.rs
src/illuminant.rs
src/illuminant/cct.rs
src/illuminant/cie_illuminant.rs
src/illuminant/cri.rs
src/lab.rs
src/lib.rs
src/observer.rs
src/rgb.rs
src/spectrum.rs
src/xyz.rs

The purpose of this PR was primarily to hide the `error` module and re-export the one and only type it contained in the crate root instead. This does not cause the crate root to have a larger API surface (replace one module for one type) and it provides easier access to this one type that is used all over the place.
I also decided to suggest renaming `CmtError` to just `Error`. It's very common that a library that has one error type it collects everything that can go wrong into just calls it `Error`. It still has more information in the full path `colorimetry::Error`. And anyone using it in an already clobbered namespace can either refer to it by it's full (but still pretty short) path, or they can import it with a rename `use colorimetry::Error as ColorimetryError` if they prefer.

Re-export the error type in the crate root, and rename it to `Error`

---

src/cam.rs
src/cam/cam16.rs
src/cam/viewconditions.rs
src/colorant/munsell_matt.rs
src/illuminant/cct.rs
src/illuminant/cri.rs
src/lib.rs
src/spectrum.rs

Explicitly allowing some dead code that is not yet used. I was balancing between adding explicit `#[allow(dead_code)]` (like in this PR and commenting out said code or deleting it. But given that these are likely things you want to use soon, and that the following solution allows for the code to still be checked in the CI during development, I opted for this solution :) If you don't think these things will be used at all or soon, we can also consider deleting them.
Having `#![allow(dead_code)]` on a global crate level has the downside of making it easy to forget old code laying around after doing refactoring and other stuff. So if possible, it would be nice to not allow it globally. Some of these lint allowances might have made it easier during some early prototyping/refactoring. But I …

Remove dead_code from global crate lint allow list

---

Cargo.toml
src/cam/cam16.rs
src/cam/viewconditions.rs
src/colorant/munsell_matt.rs
src/colorant/tcs.rs
src/error.rs
src/illuminant.rs
src/illuminant/cct.rs
src/illuminant/cie_illuminant.rs
src/illuminant/cri.rs
src/illuminant/wasm.rs
src/lab.rs
src/lib.rs
src/math.rs
src/observer.rs
src/rgb.rs
src/rgb/gamma.rs
src/rgb/rgbspace.rs
src/rgb/widergb.rs
src/spectrum.rs
src/spectrum/wasm.rs
src/xyz.rs
src/xyz/chromaticity.rs
src/xyz/dominant.rs
src/xyz/wasm.rs

This moves wasm specific code to their own modules and makes all wasm related code conditionally compiled behind cfg gates for that target. This allows us to build the library on non-wasm targets without depending on `js-sys` and `wasm-bindgen`. This brings down the dependency tree size for users who don't use this library as wasm.
I think the moving of wasm specific code into their own modules is good for structure as well. I'm not trying to make wasm a lower priority here. Quite the opposite. By letting it have their own modules it becomes easier to get an overview of the JS-API as well as extend it IMO. Separation of concerns :sparkles: 
I also updated some documentation, since it was very outdated for certain `*_js` methods.
This PR currently builds on top of the …

Stop depending on wasm-bindgen and js-sys on non-wasm targets

---

examples/spectral_locus.rs
src/observer.rs
src/observer/observers.rs
src/rgb/rgbspace.rs

The color matching function data is fixed. The computation of the spectral locus range only depend on this fixed data. The spectral locus min/max range will always be the same. So computing it at runtime for every new process that runs this library is a waste. And guarding every single access to the range behind a thread safe init check is a waste. I have looked a little bit into trying to make the computation a `const fn` so we could compute it at compile time. But Rust is not there yet. A lot of trigonometry would need to be const for example, and it just isn't.
So the backup solution that this PR proposes is to hardcode these known ranges, and verify they are correct via tests. This allows getting rid of the `OnceLock` as well as the need for computing this fixed range on first use at …

Hardcode spectral locus range to simplify and speed up code

---

CHANGELOG.md
src/cam/cam02.rs
src/cam/cam16.rs
src/illuminant.rs
src/illuminant/cct.rs
src/illuminant/cri.rs
src/lab.rs
src/observer.rs
src/observer/observers.rs
src/rgb.rs
src/rgb/rgbspace.rs
src/rgb/widergb.rs
src/spectrum.rs
src/stimulus.rs
src/xyz.rs
src/xyz/wasm.rs

There is an inconsistent use of `ObserverData` and `Observer` in the API, which is confusing for users. Here, I have replaced all instances of `&ObserverData` in the public API with `Observer`, which is an `enum`, and use the `Observer.data()` method to access its data.
I have also renamed the `Observer` items from using the `Std` prefix to using the `Cie` prefix, which is commonly used to refer to CIE standard observers.

Replace all API `&ObserverData` types with `Observer`

---

README.md
examples/cri.rs
examples/primaries.rs
examples/spectral_locus.rs
src/cam.rs
src/cam/cam02.rs
src/cam/cam16.rs
src/colorant.rs
src/colorant/tcs.rs
src/illuminant.rs
src/illuminant/cct.rs
src/illuminant/cfi.rs
src/illuminant/cie_illuminant.rs
src/illuminant/cri.rs
src/lab.rs
src/observer.rs
src/observer/observers.rs
src/prelude.rs
src/rgb.rs
src/rgb/rgbspace.rs
src/rgb/widergb.rs
src/spectrum.rs
src/stimulus.rs
src/traits.rs
src/xyz.rs
src/xyz/dominant.rs

Following up on a suggestion from @faern.
This avoids further confusion with users about when to use `ObserverData` and `Observer`.
Additionally, I moved all implementations of `ObserverData` to `Observer` to avoid code duplication.

Remove ObserverData from Public API

---

CHANGELOG.md
README.md
src/cam.rs
src/cam/cam02.rs
src/cam/cam16.rs
src/cam/viewconditions.rs
src/colorant/tcs.rs
src/lab.rs
src/lib.rs
src/observer.rs
src/xyz.rs

The example illustrates the spectral colorimetry capabilities of the library. It describes how to use the CIECAM16 model in combination with the CIE 2015 10 ° observer to match a real-world paint color, painted on a wall, with a 3000K LED illuminant, to an RGB color, when viewed on an sRGB display.
Also adding convenience functions such as `CieCam16::rgb` and simplifying the `ViewConditions` API to make it easier to use these. In particular, `ViewConditions::average_surround` and its siblings `dim_surround` and `dark_surround` make it much easier to experiment with these.

Adding Spectral Color Management Example on Colorimetry's main page

---

CHANGELOG.md
src/cam.rs
src/error.rs
src/illuminant/cie_illuminant.rs
src/observer.rs
src/rgb/rgbspace.rs

Currently (before this PR), I could write a library that depend on `colorimetry` with all features disabled. I could then write code like this in my library:
```rust
match some_observer {
Observer::Cie1931 => (),
}
```
The above would compile and be fully correct. However, if someone depend on my library, and they also end up depending on `colorimetry` somewhere else in their dependency tree, and that dependency enables the `supplemental-obeservers` feature. Then suddenly my library fails to compile with:
```
error[E0004]: non-exhaustive patterns: `Observer::Cie1964`, `Observer::Cie2015` and `Observer::Cie2015_10` not covered
```
That is because adding variants to enums is a breaking change unless the enum in `#[non_exhuastive]`. [Cargo features must be additive only and not API …

Make public enums that can be expanded `#[non_exhaustive]`

---

CHANGELOG.md
src/rgb/widergb.rs

Sometimes you want to check if a `WideRgb` instance is in-gamut or not. And if it is, operate on the corresponding `Rgb` instance. This is a simple helper to do that. Since we have conversion `WideRgb -> Rgb` with channel modification I think we should also have one that guarantees channel values stays the same, but indicate out-of-gamut with the type instead (`Option<Rgb>`).
EDIT: I also added a `is_in_gamut` method. I thought it could be helpful, and it also made the implementation of `to_rgb` cleaner at the same time.

Add `WideRgb::to_rgb` method for trying to convert without changing values

---

CHANGELOG.md
README.md
src/cam.rs
src/cam/cam02.rs
src/cam/cam16.rs
src/colorant.rs
src/colorant/munsell.rs
src/illuminant/cfi.rs
src/lab.rs
src/lib.rs
src/observer.rs
src/prelude.rs
src/xyz.rs
src/xyz/rel_xyz.rs

Inspired by #91, and previous discussions on the XYZ type,  this PR introduces a **`RelXYZ`**, to represent _related_ tristimulus values— XYZ values with a common white adaptation state, represented by a white point's tristimulus. In contrast, the existing **`XYZ`** type will continue to represent _unrelated_ tristimulus values (typically direct light sources or illuminants).
- In CIE terminology, “related colors” are the foundation for all higher-level color-appearance and adaptation models.  
- By modeling related tristimulus values explicitly, we align our data structures more closely with CIECAM and other perceptual workflows.  
- Clarifies intent:  
- `XYZ` → raw, _unrelated_ tristimulus (e.g., illuminant or source)  
- `RelXYZ` → _related_ tristimulus (surface under adapted white …

Adding `RelXYZ` to represent related colors, with a common white point

---

.cargo/config.toml
Cargo.lock
Cargo.toml
README.md
pkg/README.md
src/lib.rs
xtask/Cargo.toml
xtask/src/main.rs

This PR adds a new `xtask` sub-crate to the workspace, providing a structured Rust-based interface for project-specific tasks. It helps unify tooling, enforce standards, and reduce friction for contributors.
Runs a complete set of code quality checks:
- `cargo fmt --check`
- `cargo clippy --all-targets --all-features -D warnings`
- `cargo check --all-targets`
- `cargo rdme --check` (for verifying README is in sync with RustDoc)
This command is designed for both local development and CI pipelines.
Executes tests in two configurations:
- With all features enabled
- With all default features disabled
Useful for catching regressions related to optional dependencies and feature combinations.
Builds and opens project documentation:
```bash
cargo xtask doc
```
This wraps `cargo doc …

Introduce `xtask` utility with `check`, `test`, and `doc` commands

---

src/illuminant/cfi.rs

Tries to fix #104. The paper is sadly still paywalled however. Would it be possible to, along the formal specification, also link to some public resource able to explain at least parts of this?
It's a bit weird to help implement non-open standards :sweat_smile:

Update the URL to the CIE paper on color fidelity index computation

---

src/colorant/ces_data.rs
src/illuminant/cfi.rs

I made sure the reference to `CES` was made into a clickable link. Thereby improving the discoverability of the colorants used by CFI.
I also updated the docs on the `CES` constant a bit. One thing I removed was references to a private constant that public users cannot use anyway. I also reworded it to talk about what it contains instead of that it "creates" something. I also fixed the broken link (`http:://` had two colons).

Improve CFI color patch discoverability

---

src/illuminant.rs

I'm trying to understand TM-30 and the components it involves. This lead me to the `Illuminant::cfi_reference` method. It had a lot of repeated constants. So I tried to "clean" that up to see if it would improve the code readability or not. I think this is a slight improvement.
I personally don't really see the benefit of a match statement, if no arm is actually _matching_ against anything, but rather just binds the value and performs a conditional `if` on it.
According to what standard is this method implemented? I do not have access to the paywalled standard documents. So I'm mostly trying to learn from what is available on the open web. The following youtube video seem to do two things differently here. So I'd like to ask if that's from a different standard, or if the video is simply …

Suggestion on refactoring of `Illuminant::cfi_reference`

---

CHANGELOG.md
README.md
cli/src/utils.rs
plot/src/chart/chromaticity/xy.rs
src/colorant.rs
src/illuminant.rs
src/illuminant/cct.rs
src/illuminant/cri.rs
src/illuminant/wasm.rs
src/lab.rs
src/lab/gamut.rs
src/lab/lch.rs
src/lib.rs
src/observer.rs
src/rgb.rs
src/rgb/widergb.rs
src/spectrum.rs
src/xyz.rs
src/xyz/rel_xyz.rs
src/xyz/wasm.rs
xtask/src/gen_rgbspace.rs

The method name `values` was too generic and did not clearly convey that it produces a new owned array.  
This pull request renames these methods to `to_array`, which follows Rust naming conventions and makes the intent explicit: the method returns a fresh `[f64; 3]` rather than a reference.
**Note:**  
`to_array` was chosen over `as_array` because the method produces a new owned value.  
By convention, `as_*` is used for cheap, reference-based views, while `to_*` is used for owned conversions.

Rename "values" array methods to "to_array"

---

src/illuminant.rs
src/illuminant/qth.rs
src/traits.rs

Quartz Tungsten Halogen lamps, such as the FEL 1000W lamp, are often used for calibration purposes. This PR adds a spectral model, as described by Ojanen in 2012, which closely matches the actual spectral distributions of these lamps, with only two parameters: Filament Temperature and a scale factor, representing the measurement geometry (distance and orientation of the detector plane to the lamp).
The filament temperature is derived from a correlated color temperature, which can in turn be measured with a colorimeter, or from electrical measurements, as suggested by Ojanen.
- M. Ojanen et all., Metrologia 49 (2012) S53–S58
- J.C De Vos, Physica 20, 690 (1954)
- M. Pon and Jan P. Hessler, Applied Optics 23, 7, 975-978 (1984).

Add Quartz Tungsten Halogen (QTH) Illuminant model
